services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "password"
    volumes:
        - ./volume/rabbitmq/data/:/var/lib/rabbitmq/
        - ./volume/rabbitmq/log/:/var/log/rabbitmq


